# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='huangse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=600, verbose_name='标题名称：')),
                ('urls', models.URLField(max_length=1200, verbose_name='片地址：')),
            ],
        ),
    ]
