# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huangse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='souci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titstr', models.CharField(max_length=200, verbose_name='搜索关键词')),
            ],
        ),
        migrations.AlterModelOptions(
            name='huangse',
            options={'verbose_name': '视频名称', 'verbose_name_plural': '视频名称'},
        ),
        migrations.AlterField(
            model_name='huangse',
            name='titles',
            field=models.CharField(max_length=600, verbose_name='标题名称'),
        ),
        migrations.AlterField(
            model_name='huangse',
            name='urls',
            field=models.URLField(max_length=1200, verbose_name='片地址'),
        ),
    ]
